name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - develop
      - preproduction
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: npm install

      - name: Set Angular environment
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            echo "ANGULAR_ENV=development" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "preproduction" ]]; then
            echo "ANGULAR_ENV=preProduction" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            echo "ANGULAR_ENV=production" >> $GITHUB_ENV
          fi

      - name: Build Angular app
        run: npm run build -- --configuration=$ANGULAR_ENV

      - name: Set Firebase project
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            firebase use --token ${{ secrets.FIREBASE_TOKEN }} fidelity-back;
          elif [[ "${{ github.ref_name }}" == "preproduction" ]]; then
            firebase use --token ${{ secrets.FIREBASE_TOKEN }} fidelity-back-pre;
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            firebase use --token ${{ secrets.FIREBASE_TOKEN }} fidelity-back-pro;
          fi

      - name: Deploy to Firebase Hosting
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            firebase deploy --only hosting:fidely-admin --token ${{ secrets.FIREBASE_TOKEN }};
          elif [[ "${{ github.ref_name }}" == "preproduction" ]]; then
            firebase deploy --only hosting:fidely-admin-pre --token ${{ secrets.FIREBASE_TOKEN }};
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            firebase deploy --only hosting:fidely-admin --token ${{ secrets.FIREBASE_TOKEN }};
          fi
