name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - develop
      - preproduction
      - master  # Para producción

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Chequear el código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Instalar Node.js y dependencias
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # 3. Construir el proyecto Angular
      - name: Build Angular app
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            ng build -c=development;
          elif [[ "${{ github.ref_name }}" == "preproduction" ]]; then
            ng build -c=preProduction;
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            ng build -c=production;
          fi

      # 4. Autenticarse con Firebase según la rama
      - name: Set Firebase project
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            firebase use --token ${{ secrets.FIREBASE_TOKEN }} fidelity-back;
          elif [[ "${{ github.ref_name }}" == "preproduction" ]]; then
            firebase use --token ${{ secrets.FIREBASE_TOKEN }} fidelity-back-pre;
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            firebase use --token ${{ secrets.FIREBASE_TOKEN }} fidelity-back-pro;
          fi

      # 5. Desplegar a Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: |
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            firebase deploy --only hosting:fidely-admin --token ${{ secrets.FIREBASE_TOKEN }};
          elif [[ "${{ github.ref_name }}" == "preproduction" ]]; then
            firebase deploy --only hosting:fidely-admin-pre --token ${{ secrets.FIREBASE_TOKEN }};
          elif [[ "${{ github.ref_name }}" == "master" ]]; then
            firebase deploy --only hosting:fidely-admin --token ${{ secrets.FIREBASE_TOKEN }};
          fi
